# Generated by Django 3.1.1 on 2020-10-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0009_auto_20201001_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='media/default', upload_to='media/Profiles'),
        ),
    ]
