# Generated by Django 3.0.3 on 2020-09-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
